# -*- coding: utf-8 -*-
"""bigquery1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxcR5dZevN67hRWFbTsaL1VYiizpNQhT
"""

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery --project projectname df1
# select * from dataset1.employees

df1.tail()